{% set name = "civetweb" %}
{% set version = "1.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: a7ccc76c2f1b5f4e8d855eb328ed542f8fe3b882a6da868781799a98f4acdedc

build:
  number: 1
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.5.1,<4
    - ninja >=1.10,<2
    - patch
    - pkgconfig
  host:
    - openssl

test:
  commands:
    - test -x ${PREFIX}/bin/civetweb
    - test -f ${PREFIX}/include/{{ name }}.h
    - test -d ${PREFIX}/lib/cmake/{{ name }}
    - test -f ${PREFIX}/lib/lib{{ name }}.so
    - test -f ${PREFIX}/lib/lib{{ name }}-cpp.so

about:
  home: https://github.com/civetweb/civetweb
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'An easy to use C/C++ embeddable web server.'
  dev_url: https://github.com/civetweb/civetweb

extra:
  recipe-maintainers:
    - sodre
